/**
*  Description     :  Interface class example
*
*  Created By      :  Mrinal Das
*
*  Created Date    :  06/30/2022
*
*  Revision Logs   :    V1.0 - Created - Mrinal Das
*				      
*
**/

public interface ApexInterfacesProductExample {
    
         /**
         * 
         *   @description    :   Method of Interface for model number
         *
         *   @args           :   
         *
         *   @return         :   void
         *
         *   @revision Log   :   V1.1 - Created  - 06/30/2022 - Mrinal Das
         *		              
        * 
        **/
    
    String getModelNumber();
}