/**
*  Description     :   An interface that defines what a purchase order looks like in general
*
*  Created By      :  Mrinal Das
*
*  Created Date    :  06/29/2022
*
*  Revision Logs   :    V1.0 - Created - Mrinal Das
*				      
*
**/

public interface PurchaseOrder {
    /**
     * 
     *   @description    :   Method of Interface to Provide a Discount
     *
     *   @args           :   
     *
     *   @return         :   void
     *
     *   @revision Log   :   V1.1 - Created  - 06/29/2022 - Mrinal Das
     *		              
     * 
     **/

    Double discount();
}